### ISSUE TITLE
Core

### ISSUE THREAD

**Issue by Murren7** [deathbeam/maps-of-exile#14]
### Issue description

How come boss with long phases is "boss rushable" + you have to kill 3 mini-bosses before you kill map boss

### Map name

Core

### Layout rating

None

### Density rating

None

### Boss rating

1

### Layout

- [ ] **League mechanics** - If map is good for league mechanics that require some space (Breach, Legion)
- [ ] **Delirium mirror** - If you can hold delirium mirror through whole map or delirium mirror gets good value in it
- [ ] **Outdoors** - If map is outdoors or indoors (Dunes vs Cells for example)
- [ ] **Linear** - If map is linear instead of having multiple paths to take. Map counts as linear even if the line goes in circle
- [ ] **Few obstacles** - If map does not have a lot of obstacles (so for example is good for shield charging around)

### Boss

- [ ] **Not spawned** - If boss is not spawned on entering the map (important for Altar farming, can be verified by checking for boss altars spawning or not)
- [ ] **Rushable** - If boss is close to map start or can be rushed quickly and reliably, a lot quicker than completing whole map
- [X] **Phases** - If boss has hard phases that force you to wait (delay on initial boss spawn counts too)
- [ ] **Soft phases** - If boss has soft phases that can be bypassed with DPS (teleports at certain threshold, heals, partial damage reduction)
- [ ] **Separated** - If boss room is separated from rest of the map

**Comment by deathbeam** [comment]
![image](https://github.com/deathbeam/maps-of-exile/assets/5115805/53ed60ad-35de-4af2-85d7-e0c118102a60)

Core specifically has this tooltip, in elder guardian maps those bosses are already dead so you can just enter afaik.

**Comment by deathbeam** [comment]
Decded to unmark Core as rushable as it was more confusing for ppl than helpful
