### ISSUE TITLE
Suggestion : a option to hide non droppable cards and cards bellow minimum card price.

### ISSUE THREAD

**Issue by jihed123** [deathbeam/maps-of-exile#15]
- Adding a way to hide low priced cards and non droppable cards will improve visibility. 

- Adding sorting by layout,density,boss rating will also improve experience.

**Comment by deathbeam** [comment]
Opened separate issue #17 for your second point and implemented first one:

![image](https://github.com/deathbeam/maps-of-exile/assets/5115805/9df4971a-5bbc-480d-9c66-e1e2534532ee)
