### ISSUE TITLE
Request: Add Filter for Kirac Divination Card Strategy

### ISSUE THREAD

**Issue by palidintank** [deathbeam/maps-of-exile#16]
Is it possible to add a flag/filter to change weighting of divination cards to be based on the full stack size.

This is to take advantage of the strategy using Kirac missions for dropping divination cards as a full stack.

**Comment by deathbeam** [comment]
Should be there now:

![image](https://github.com/deathbeam/maps-of-exile/assets/5115805/42e96541-9c34-4915-8625-dc9d35df6c67)
