### ISSUE TITLE
Adding sorting by layout,density,boss rating will also improve experience.

### ISSUE THREAD

**Issue by deathbeam** [deathbeam/maps-of-exile#17]
From issue #15 so it do not contains multiple things at once

**Comment by melink14** [comment]
I was also thinking about this. I actually want to reverse sort in order to find maps for shadow sniping. :)

**Comment by deathbeam** [comment]
Also mention from reddit, additional sorting based on card rarity for card view might also be useful. I want to look at adding proper sort system at some point but I really dont like the table header sorting as its fairly limited, need to figure out something nicer
