### ISSUE TITLE
Stagnation

### ISSUE THREAD

**Issue by Boxxerz** [deathbeam/maps-of-exile#22]
### Issue description

Azyran's Reward seems to have a MUCH lower drop rate..

I'm running full quant build + Div scarabs ect ect

Currently have:
5/5 The Tinker's Table (1:50 maps)
5/8 The Scout (1:48 maps)
2/9 Azyran's Reward (1:27 maps)

Feels like Azyran's CAN'T be 1:27 average when I have so many more of the rarer cards...

### Map name

Stagnation

### Layout rating

None

### Density rating

None

### Boss rating

None

### Layout

- [ ] **League mechanics** - If map is good for league mechanics that require some space (Breach, Legion)
- [ ] **Delirium mirror** - If you can hold delirium mirror through whole map or delirium mirror gets good value in it
- [ ] **Outdoors** - If map is outdoors or indoors (Dunes vs Cells for example)
- [ ] **Linear** - If map is linear instead of having multiple paths to take. Map counts as linear even if the line goes in circle
- [ ] **Few obstacles** - If map does not have a lot of obstacles (so for example is good for shield charging around)

### Boss

- [ ] **Not spawned** - If boss is not spawned on entering the map (important for Altar farming, can be verified by checking for boss altars spawning or not)
- [ ] **Rushable** - If boss is close to map start or can be rushed quickly and reliably, a lot quicker than completing whole map
- [ ] **Phases** - If boss has hard phases that force you to wait (delay on initial boss spawn counts too)
- [ ] **Soft phases** - If boss has soft phases that can be bypassed with DPS (teleports at certain threshold, heals, partial damage reduction)
- [ ] **Separated** - If boss room is separated from rest of the map

**Comment by deathbeam** [comment]
Should be hopefully solved with b4a9852 , switched to sligthly more accurate card spreadsheet
