### ISSUE TITLE
Any out of atlas map doesnt respect voidstones option

### ISSUE THREAD

**Issue by Shidzy2** [deathbeam/maps-of-exile#32]
### Issue description

When you pick voidstiones number, maps that out of current atlas doesnt changed according to watchstones count,
as i understand that you cant predict what tier they be on 1-3 voidstones, at 4 they always should be t16, 
additional proposition: 
0 voidstones - always t1,
1 voistone - always t5,
2 voidstones - always t9,
3 voidstones - always t13,
4 voidstones - always t16,
![image](https://github.com/deathbeam/maps-of-exile/assets/45227075/c8fcd115-e0ff-4372-b6f2-b819fa7f646d)

### Map name

None

### Layout rating

None

### Density rating

None

### Boss rating

None

### Tags

- [ ] **League mechanics** - If map is good for league mechanics that require some space (Breach, Legion)
- [ ] **Delirium mirror** - If you can hold delirium mirror through whole map or delirium mirror gets good value in it
- [ ] **Outdoors** - If map is outdoors or indoors (Dunes vs Cells for example)
- [ ] **Linear** - If map is linear instead of having multiple paths to take. Map counts as linear even if the line goes in circle
- [ ] **Few obstacles** - If map does not have a lot of obstacles (so for example is good for shield charging around)
- [ ] **Boss Not spawned** - If boss is not spawned on entering the map (important for Altar farming, can be verified by checking for boss altars spawning or not)
- [ ] **Boss Rushable** - If boss is close to map start or can be rushed quickly and reliably, a lot quicker than completing whole map
- [ ] **Boss Phases** - If boss has hard phases that force you to wait (delay on initial boss spawn counts too)
- [ ] **Boss Soft phases** - If boss has soft phases that can be bypassed with DPS (teleports at certain threshold, heals, partial damage reduction)
- [ ] **Boss Separated** - If boss room is separated from rest of the map

**Comment by deathbeam** [comment]
Well the out of atlas maps move in tiers I think right? So applying voidstones to them did not rly made sense to me as the tier might change too. But maybe im wrong on this.

**Comment by Shidzy2** [comment]
But tier and area level is necessary for kirak strategy as some cards stop dropping after certain area level, also out of atlas maps are not moving in tiers as they out of atlas so their future tier is not known
