### ISSUE TITLE
Plaza

### ISSUE THREAD

**Issue by sup3rmanzzz** [deathbeam/maps-of-exile#33]
### Issue description

Map boss is rated way too highly. With witnessing and maven adding other bosses etc this boss can be a real pain in the ass. Especially if u witness it and bring it along to an invitation. when there is a million other things going on within the boss arena that beam is one of the most annoying boss abilities in the game IMO, can legit be impossible to survive if some other boss/mob is slowing you at the same time. Plaza boss is the bane of my existence. Please reduce to a 2 or 3 at most so that I may sleep at night. Ofc this is an opinion feel free to ignore me.

### Map name

Plaza

### Layout rating

4

### Density rating

None

### Boss rating

1

### Tags

- [ ] **League mechanics** - If map is good for league mechanics that require some space (Breach, Legion)
- [ ] **Delirium mirror** - If you can hold delirium mirror through whole map or delirium mirror gets good value in it
- [ ] **Outdoors** - If map is outdoors or indoors (Dunes vs Cells for example)
- [ ] **Linear** - If map is linear instead of having multiple paths to take. Map counts as linear even if the line goes in circle
- [ ] **Few obstacles** - If map does not have a lot of obstacles (so for example is good for shield charging around)
- [ ] **Boss Not spawned** - If boss is not spawned on entering the map (important for Altar farming, can be verified by checking for boss altars spawning or not)
- [ ] **Boss Rushable** - If boss is close to map start or can be rushed quickly and reliably, a lot quicker than completing whole map
- [ ] **Boss Phases** - If boss has hard phases that force you to wait (delay on initial boss spawn counts too)
- [ ] **Boss Soft phases** - If boss has soft phases that can be bypassed with DPS (teleports at certain threshold, heals, partial damage reduction)
- [ ] **Boss Separated** - If boss room is separated from rest of the map

**Comment by deathbeam** [comment]
Agreed, adjusted the rating to 2
