### ISSUE TITLE
Burial chambers

### ISSUE THREAD

**Issue by darthcid** [deathbeam/maps-of-exile#34]
### Issue description

Ive run over 600 fully juiced burials in this league so far and im certain doctor drop rate is heavily nerfed. The Fortunate was quite correct compared to dragons heart but 22 dragons heart compared to 2 doctors does not at all represent the 15 to 18 weighting the website states. Fortunates were above 1500 so that fits compared to dragons heart. Maybe I was just incredibliest unlucky but that would be so far of an outlier that doctor must have been nerfed

### Map name

None

### Layout rating

None

### Density rating

None

### Boss rating

None

### Tags

- [ ] **League mechanics** - If map is good for league mechanics that require some space (Breach, Legion)
- [ ] **Delirium mirror** - If you can hold delirium mirror through whole map or delirium mirror gets good value in it
- [ ] **Outdoors** - If map is outdoors or indoors (Dunes vs Cells for example)
- [ ] **Linear** - If map is linear instead of having multiple paths to take. Map counts as linear even if the line goes in circle
- [ ] **Few obstacles** - If map does not have a lot of obstacles (so for example is good for shield charging around)
- [ ] **Boss Not spawned** - If boss is not spawned on entering the map (important for Altar farming, can be verified by checking for boss altars spawning or not)
- [ ] **Boss Rushable** - If boss is close to map start or can be rushed quickly and reliably, a lot quicker than completing whole map
- [ ] **Boss Phases** - If boss has hard phases that force you to wait (delay on initial boss spawn counts too)
- [ ] **Boss Soft phases** - If boss has soft phases that can be bypassed with DPS (teleports at certain threshold, heals, partial damage reduction)
- [ ] **Boss Separated** - If boss room is separated from rest of the map

**Comment by deathbeam** [comment]
Card weights are sourced from prohibited library so if you are certain please report your findings there: https://discord.gg/3VxKY6gt7j
