### ISSUE TITLE
Card Sources not updated for 3.25 - Settlers League

### ISSUE THREAD

**Issue by willooooo** [deathbeam/maps-of-exile#49]
website is still using the old league's card location info. Poewiki is updated with the new card locations.

Example:

Burial Chamber:

-mapsofexile:
shows The Fortunate, The Doctor, and various other cards.

-poewiki:
shows Cursed Words, The Thaumaturgist, The Brawny Battle Mage, Brother's gift

**Comment by deathbeam** [comment]
The update from wiki (and other sources) runs every day, if wiki is updated the automated build should update it soon-ish. I started the manual update anyway so should bethere in few mins
